server:
  port: 10010


# 服務名
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user #唯一id
          uri: http://localhost:9101
          predicates:
            - RbacAuth=rbac
#            - Path=/user/**
#            - Header=Authorization
#            - Header=test
          filters:
            - AddRequestHeader=Authorization, Jason
            - AddRequestParameter=name, Johnson
            - IpForbid=192.168.0.102 #名稱為 該filter class 的 gateway 之前的名字


